name: mood_app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  build_runner: ^2.4.14
  connectivity_plus: ^6.1.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_local_notifications: ^18.0.1
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  status_bar_control: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
